from __future__ import annotations
import typing


MIN_NAME_LENGTH: typing.Final = 8

VERB_PREFIXES: typing.Final = {
    "validate",
    "test",
    "execute",
    "visit",
    "get",
    "cancel",
    "retrieve",
    "lock",
    "assert",
    "extract",
    "enrich",
    "run",
    "patch",
    "build",
    "start",
    "ping",
    "prepare",
    "publish",
    "request",
    "ack",
    "nack",
    "reject",
    "stop",
    "route",
    "begin",
    "subscribe",
    "connect",
    "close",
    "enter",
    "exit",
    "take",
    "dump",
    "iter",
    "escape",
    "unescape",
    "add",
    "contains",
    "unsubscribe",
    "resubscribe",
    "commit",
    "raise",
    "mock",
    "produce",
    "consume",
    "track",
    "wait",
    "bootstrap",
    "calculate",
    "check",
    "collect",
    "compute",
    "convert",
    "create",
    "delete",
    "fetch",
    "find",
    "format",
    "generate",
    "handle",
    "has",
    "is",
    "list",
    "load",
    "make",
    "parse",
    "process",
    "read",
    "receive",
    "remove",
    "render",
    "resolve",
    "save",
    "send",
    "set",
    "should",
    "update",
    "write",
    "obtain",
    "perform",
    "override",
    "upload",
    "copy",
    "register",
    "utter",
    "authenticate",
    "record",
    "observe",
    "upgrade",
    "downgrade",
    "do",
    "reset",
    "open",
    "use",
    "assemble",
    "compile",
    "choose",
    "call",
    "filter",
    "apply",
    "measure",
    "ensure",
    "submit",
    "clear",
    "undo",
    "cache",
    "fill",
    "import",
    "match",
    "push",
    "merge",
    "store",
    "transform",
    "verify",
    "wrap",
    "unwind",
    "replay",
    "synchronize",
    "count",
}

SCALAR_ANNOTATIONS: typing.Final = {"int", "str", "float", "bool", "bytes", "complex"}

MAPPING_PROXY_TYPES: typing.Final = {"MappingProxyType"}

ALLOWED_STDLIB_FROM_IMPORTS: typing.Final = {"collections.abc"}

FINAL_CLASS_EXCLUDED_BASES: typing.Final = {"BaseModel", "RootModel", "ModelFactory", "SQLAlchemyFactory"}
MAX_IMPORT_NAMES: typing.Final = 2
